# -*- coding: utf-8 -*-
"""S2_IP_exercice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tbeucler/2024_UNIL_Geoinformatique/blob/main/Geoinformatique_I/IP/Exercices_IP/S2_IP_exercice.ipynb

# Exercice 2 - Structure de contrôle

## Conditions if, else, elif

**1. Vérification de la parité**
"""

# Ecrivez votre code ici
nombre = 4 #Entrez un nombre entier

if nombre % 2 == 0 :
    print("Pair")
else:
    print("Impaire")

"""**2. Comparaison de deux nombres**"""

nombre1 = 1.5 #Entrez un chiffre à virgule
nombre2 = 0.5 #Entrez un deuxième chiffre à virgule

if nombre1 > nombre2:
    print("Le premier nombre est plus grand.")
elif nombre2 > nombre1:
    print("Le deuxième nombre est plus grand.")
else:
    print("Les deux nombres sont égaux")

"""**3. Catégorisation d'âges**"""

age = 6 # Entrez un nombre entier
if age < 12:
    print("Enfant")
elif 12 <= age < 18:
    print("Adolescent")
elif 18 <= age < 65:
    print("Adulte")
else:
    print("Senior")

"""## Boucle for et while

**1. Ecrire une boucle `while` pour afficher les valeurs des classements d'une liste de lecture d'albums stockée dans la liste <code>PlayListRatings</code>. Si le score est inférieur à 6, on sort de la boucle. La liste <code>PlayListRatings</code> est donnée par : <code>PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]</code>**
"""

# Ecrivez votre code ici
PlayListRating = [10, 9.5, 10, 8, 7.5, 5, 10, 10]

# Astuce : Utilisez l'indexation de la liste comme critère (longueur de votre liste)
indx = 0
while indx<len(PlayListRating):
  if PlayListRating[indx]<6:
    break
  else:
    print(PlayListRating[indx])
  indx+=1

"""**2. Répétez ce que vous venez de faire, cette fois en utilisant une boucle `for`**."""

for indx in range(len(PlayListRating)):
  if PlayListRating[indx]<6:
    breakpoint
  else:
    print(PlayListRating[indx])

"""**3. Ecrivez une boucle `for` qui imprime (affiche) la liste suivante : <code>carres=['rouge', 'jaune', 'vert', 'violet', 'bleu']</code>**"""

carres = ['rouge', 'jaune', 'vert', 'violet', 'bleu'] # An empty list
liste = []
for color,i in enumerate(carres):
  liste.append(color) # Here you add (append) the elements one by one to the empty list

print(carres)

